In [2]:
import numpy as np

a = np.array([15, 25, 35]) 
print(type(a)) 
print(a.shape) 
print(a[0], a[1], a[2]) 
a[0] = 5 
print(a) 

b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape) 
print(b[0, 0], b[0, 1], b[1, 0]) 

a = np.zeros((2,2)) 
print(a) 
 
b = np.ones((1,2)) 
print(b) 

c = np.full((2,2), 7) 
print(c)

<class 'numpy.ndarray'>
(3,)
15 25 35
[ 5 25 35]
(2, 3)
1 2 4
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


In [3]:
d = np.eye(2) 
print(d) 

e = np.random.random((2,2)) 
print(e) 

np.array(np.mat('2 23; 30 52')) 
np.array(np.mat('5 25; 45 65'), subok=True) 

[[1. 0.]
 [0. 1.]]
[[0.61843746 0.35074804]
 [0.36196261 0.96995922]]


matrix([[ 5, 25],
        [45, 65]])

In [4]:

a = np.arange(10) 
print (a[2:5]) 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:]) 

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a[...,1]) 
print (a[1,...]) 
print (a[...,1:])

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]]
print (y) 

x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print (x[x > 5]) 

[2 3 4]
[[3 4 5]
 [4 5 6]]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
[1 4 5]
[ 6  7  8  9 10 11]


In [6]:
a = np.arange(9,dtype = np.float_).reshape(3,3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [7]:
b = np.array([10,10,10])
print(b)

[10 10 10]


In [8]:
print(np.add(a,b))

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [9]:
print(np.subtract(a,b))

[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


In [13]:
t = np.array([0.25,1.33,1,5,100])
print(t)

[  0.25   1.33   1.     5.   100.  ]


In [14]:
print(np.reciprocal(t))

[4.        0.7518797 1.        0.2       0.01     ]


In [16]:
s = np.array([100], dtype = int) 
print(s)
print(np.reciprocal(s))

[100]
[0]


In [17]:
a = np.array([10,20,30])
print(np.power(a,2))

[100 400 900]


In [18]:
a = np.array([45,50,60]) 
b = np.array([3,6,8])
print(np.mod(a,b))

[0 2 4]


In [20]:
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 
print(np.mod(a,b) )

[1 0 2]
